# Unique project key inside SonarQube
sonar.projectKey=news_website

# Name displayed in the SonarQube UI
sonar.projectName=News Website Backend
sonar.projectVersion=1.0

# Path to the source code relative to the root directory
sonar.sources=src

# Exclude test files and node_modules from main source metrics
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/*.test.js, dist/**, coverage/**

# Path to test files
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.js

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Integration with Jest LCOV Code Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info